name: Github Action with TeXLive [Full]
description: Run arbitrary commands in a TeXLive environment.
author: Cheng XU
inputs:
  run:
    description: Arbitrary bash codes to be executed
    required: true
runs:
  using: docker
  image: docker://xucheng/texlive-full:20200526
  entrypoint: /bin/bash
  args:
    - -c
    - ${{ inputs.run }}
branding:
  icon: book
  color: blue
